### ISSUE TITLE
[BUG]: Import of sonatypeiq_source_control fails

### ISSUE THREAD

**Issue by grahamhar** [sonatype-nexus-community/terraform-provider-sonatypeiq#33]
### Expected Behavior

The resource should have been imported. This has failed on 2 resources I have tried to import, I will attempt to do further testing as I worked around the issue by deleting the configuration using the rest API and then recreating.

If there isn't sufficient debug output I will do a PR to add that.

### Actual Behavior

The provider crashed, see output below.

### Sonatype IQ Server Version

175

### Terraform Version

1.8.5

### Affected Resource(s)

sonatypeiq_source_control

### Panic Output

```shell
Stack trace from the terraform-provider-sonatypeiq_v0.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x154eb00]

goroutine 376 [running]:
terraform-provider-sonatypeiq/internal/provider.(*sourceControlResource).Read(0xc0006ed530, {0x1b03448, 0xc0006ed4a0}, {{{{0x1b077d0, 0xc0000a4ab0}, {0x18aace0, 0xc0000a45a0}}, {0x1b09128, 0xc0000a3a40}}, 0xc0003bc060, ...}, ...)
        terraform-provider-sonatypeiq/internal/provider/source_control_resource.go:205 +0x520
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0001a6dc0, {0x1b03448, 0xc0006ed4a0}, 0xc0006ed560, 0xc00037d6c8)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_readresource.go:101 +0x64e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0001a6dc0, {0x1b03448?, 0xc0006ed380?}, 0xc00071f500)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_readresource.go:55 +0x3e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0002528c0, {0x1b03448?, 0xc0006ec9f0?}, 0xc000740ae0)
        github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov6/tf6server/server.go:776 +0x4c3
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x19a3160?, 0xc0002528c0}, {0x1b03448, 0xc0006ec9f0}, 0xc0003b3d00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001bb000, {0x1b03448, 0xc0006ec960}, {0x1b08140, 0xc00040c1a0}, 0xc0004e26c0, 0xc000335290, 0x21249c8, 0x0)
        google.golang.org/grpc@v1.61.1/server.go:1385 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0001bb000, {0x1b08140, 0xc00040c1a0}, 0xc0004e26c0)
        google.golang.org/grpc@v1.61.1/server.go:1796 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 36
        google.golang.org/grpc@v1.61.1/server.go:1040 +0x135

Error: The terraform-provider-sonatypeiq_v0.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grahamhar** [comment]
I have identified the issue and will work on a pull request to fix the issue
